In [1]:
import pandas as pd

In [2]:
from sklearn.neighbors import KNeighborsClassifier as KNN

In [13]:
x=pd.DataFrame([1,2,4,2,5,6,7,8,10])
y=[10,20,30,40,50,60,70,80,90]

In [14]:
model=KNN(n_neighbors=4)

In [15]:
model.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [16]:
model.score(x,y)

0.2222222222222222

In [18]:
model.predict(x)

array([10, 10, 30, 10, 30, 50, 50, 60, 60])

In [20]:
a=pd.DataFrame([90])
model.predict(a)

array([60])

In [21]:
df=pd.read_csv("train_LZV4RXX.csv")

In [22]:
df

loan_id  age  education proof_submitted  loan_amount  asset_cost  \
0           1   27        1.0          Aadhar       504264      820920   
1           2   48        1.0          Aadhar       728556      831444   
2           3   30        2.0         VoterID       642936      826092   
3           4   28        1.0          Aadhar       746556      930924   
4           5   29        1.0          Aadhar      1139880     1902000   
...       ...  ...        ...             ...          ...         ...   
6995     6996   45        2.0          Aadhar       930948     1258344   
6996     6997   41        2.0          Aadhar       681108      791040   
6997     6998   47        2.0          Aadhar       627636      720336   
6998     6999   39        1.0          Aadhar       654708      793860   
6999     7000   31        1.0          Aadhar       705108      900660   

      no_of_loans  no_of_curr_loans  last_delinq_none  loan_default  
0               2                 2                 0             0  
1               6                 2                 0             0  
2               0                 0                 0             1  
3               0                 0                 0             0  
4               0                 0                 0             0  
...           ...               ...               ...           ...  
6995            0                 0                 0             1  
6996            4                 4                 0             1  
6997           35                11                 0             1  
6998            0                 0                 0             1  
6999            0                 0                 0             0  

[7000 rows x 10 columns]

In [24]:
x=df[["age","loan_amount","asset_cost","no_of_loans","no_of_curr_loans"]].values.reshape(-1,5)

In [25]:
y=df["loan_default"]

In [27]:
from sklearn.model_selection import train_test_split

In [30]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=56)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [40]:
train_x.shape,test_x.shape

((4900, 5), (2100, 5))

In [29]:
model.fit(train_x,train_y)

In [32]:
model.score(train_x,train_y)

0.720204081632653

In [34]:
pre=model.predict(train_x)

In [35]:
model.score(train_x,pre)

1.0

In [37]:
test_pre=model.predict(test_x)

In [41]:
test_pre

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
model.score(test_x,test_pre)

1.0